// Generated by scripts/generate-request-kinds.ts — do not edit by hand
import type { sheets_v4 } from "googleapis";

export const BATCH_UPDATE_REQUEST_KINDS = [
  "addBanding",
  "addChart",
  "addConditionalFormatRule",
  "addDataSource",
  "addDimensionGroup",
  "addFilterView",
  "addNamedRange",
  "addProtectedRange",
  "addSheet",
  "addSlicer",
  "addTable",
  "appendCells",
  "appendDimension",
  "autoFill",
  "autoResizeDimensions",
  "cancelDataSourceRefresh",
  "clearBasicFilter",
  "copyPaste",
  "createDeveloperMetadata",
  "cutPaste",
  "deleteBanding",
  "deleteConditionalFormatRule",
  "deleteDataSource",
  "deleteDeveloperMetadata",
  "deleteDimension",
  "deleteDimensionGroup",
  "deleteDuplicates",
  "deleteEmbeddedObject",
  "deleteFilterView",
  "deleteNamedRange",
  "deleteProtectedRange",
  "deleteRange",
  "deleteSheet",
  "deleteTable",
  "duplicateFilterView",
  "duplicateSheet",
  "findReplace",
  "insertDimension",
  "insertRange",
  "mergeCells",
  "moveDimension",
  "pasteData",
  "randomizeRange",
  "refreshDataSource",
  "repeatCell",
  "setBasicFilter",
  "setDataValidation",
  "sortRange",
  "textToColumns",
  "trimWhitespace",
  "unmergeCells",
  "updateBanding",
  "updateBorders",
  "updateCells",
  "updateChartSpec",
  "updateConditionalFormatRule",
  "updateDataSource",
  "updateDeveloperMetadata",
  "updateDimensionGroup",
  "updateDimensionProperties",
  "updateEmbeddedObjectBorder",
  "updateEmbeddedObjectPosition",
  "updateFilterView",
  "updateNamedRange",
  "updateProtectedRange",
  "updateSheetProperties",
  "updateSlicerSpec",
  "updateSpreadsheetProperties",
  "updateTable",
] as const satisfies ReadonlyArray<keyof sheets_v4.Schema$Request>;

export type BatchUpdateRequestKind =
  (typeof BATCH_UPDATE_REQUEST_KINDS)[number];

type MissingInRegistry = Exclude<
  keyof sheets_v4.Schema$Request,
  BatchUpdateRequestKind
>;
type ExtraInRegistry = Exclude<
  BatchUpdateRequestKind,
  keyof sheets_v4.Schema$Request
>;
type AssertRegistryMatchesGoogleapis = MissingInRegistry extends never
  ? ExtraInRegistry extends never
    ? true
    : never
  : never;
const _registryMatchesGoogleapis: AssertRegistryMatchesGoogleapis = true;
