#!/usr/bin/env bun
/**
 * Regenerates src/api/request-types.ts from googleapis Schema$Request keys.
 * Run after bumping the googleapis dependency: bun scripts/generate-request-kinds.ts
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { extractBatchUpdateRequestKindsFromDts } from "../src/api/googleapis-request-kinds";

const ROOT = join(import.meta.dir, "..");
const kinds = extractBatchUpdateRequestKindsFromDts();
const lines = kinds.map((k) => `  "${k}",`).join("\n");

const contents = `// Generated by scripts/generate-request-kinds.ts — do not edit by hand
import type { sheets_v4 } from "googleapis";

export const BATCH_UPDATE_REQUEST_KINDS = [
${lines}
] as const satisfies ReadonlyArray<keyof sheets_v4.Schema$Request>;

export type BatchUpdateRequestKind =
  (typeof BATCH_UPDATE_REQUEST_KINDS)[number];

type MissingInRegistry = Exclude<
  keyof sheets_v4.Schema$Request,
  BatchUpdateRequestKind
>;
type ExtraInRegistry = Exclude<
  BatchUpdateRequestKind,
  keyof sheets_v4.Schema$Request
>;
type AssertRegistryMatchesGoogleapis = MissingInRegistry extends never
  ? ExtraInRegistry extends never
    ? true
    : never
  : never;
const _registryMatchesGoogleapis: AssertRegistryMatchesGoogleapis = true;
`;

writeFileSync(join(ROOT, "src/api/request-types.ts"), contents);
console.log(`Wrote ${kinds.length} request kinds to src/api/request-types.ts`);
